# Generated by Django 5.0 on 2024-02-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='link_img',
            field=models.CharField(max_length=60, null=True, verbose_name='اسم عکس'),
        ),
    ]
