# Generated by Django 5.0 on 2024-02-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_products_link_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام کاربری')),
                ('email', models.CharField(max_length=30, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
        ),
    ]
